{"_notifyingListeners":false,"_scopeListeners":[],"_eventProcessors":[],"_breadcrumbs":[{"timestamp":1626100616.686,"category":"electron","message":"app.ready","type":"ui"},{"timestamp":1626100616.735,"category":"electron","message":"app.-session-created","type":"ui"},{"timestamp":1626100616.736,"category":"electron","message":"app.session-created","type":"ui"},{"timestamp":1626100616.739,"category":"electron","message":"app.web-contents-created","type":"ui"},{"timestamp":1626100616.748,"category":"electron","message":"app.browser-window-created","type":"ui"},{"timestamp":1626100617.2,"category":"console","level":"error","message":"(node:2) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead."},{"timestamp":1626100617.215,"category":"electron","message":"app.gpu-info-update","type":"ui"},{"timestamp":1626100617.228,"category":"electron","message":"app.browser-window-focus","type":"ui"},{"timestamp":1626100617.287,"category":"console","level":"error","message":"(node:2) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated."},{"timestamp":1626100617.355,"category":"console","level":"warning","message":"(electron) 'allowRendererProcessReuse' is deprecated and will be removed."},{"timestamp":1626100617.357,"category":"console","level":"log","message":"state:  unavailable"},{"timestamp":1626100617.419,"category":"electron","message":"app.web-contents-created","type":"ui"},{"timestamp":1626100617.446,"category":"electron","message":"app.browser-window-created","type":"ui"},{"timestamp":1626100617.502,"category":"electron","message":"WebContents[1].dom-ready","type":"ui"},{"timestamp":1626100619.252,"category":"electron","message":"WebContents[2].dom-ready","type":"ui"},{"timestamp":1626100619.253,"category":"console","level":"log","message":"state:  checking"},{"timestamp":1626100619.462,"category":"electron","message":"app.remote-get-builtin","type":"ui"},{"timestamp":1626100619.464,"category":"electron","message":"app.remote-get-builtin","type":"ui"},{"timestamp":1626100619.464,"category":"electron","message":"app.remote-get-builtin","type":"ui"},{"timestamp":1626100619.465,"category":"electron","message":"app.remote-get-builtin","type":"ui"},{"timestamp":1626100619.466,"category":"electron","message":"app.remote-get-builtin","type":"ui"},{"timestamp":1626100619.475,"category":"electron","message":"app.remote-get-builtin","type":"ui"},{"timestamp":1626100619.476,"category":"electron","message":"app.remote-get-builtin","type":"ui"},{"timestamp":1626100620.187,"category":"electron","message":"app.remote-get-builtin","type":"ui"},{"timestamp":1626100620.231,"category":"electron","message":"WebContents[1].destroyed","type":"ui"},{"timestamp":1626100620.256,"category":"electron","message":"app.browser-window-focus","type":"ui"},{"timestamp":1626100620.309,"category":"electron","message":"app.remote-get-current-web-contents","type":"ui"},{"timestamp":1626100621.24,"category":"console","level":"log","message":"state:  unavailable"},{"timestamp":1626100647.814,"category":"console","level":"error","message":"(node:2) UnhandledPromiseRejectionWarning: Error: bad request\n    at buildError (<embedded>:10:497792)\n    at IncomingMessage.<anonymous> (<embedded>:10:499489)\n    at IncomingMessage.emit (events.js:310:20)\n    at IncomingMessage.EventEmitter.emit (domain.js:482:12)\n    at endReadableNT (_stream_readable.js:1187:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"},{"timestamp":1626100647.814,"category":"console","level":"error","message":"(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)"},{"timestamp":1626100647.814,"category":"console","level":"error","message":"(node:2) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code."},{"timestamp":1626100673.626,"category":"electron","message":"app.browser-window-blur","type":"ui"},{"timestamp":1626100870.07,"category":"electron","message":"app.browser-window-focus","type":"ui"},{"timestamp":1626100870.076,"category":"electron","message":"app.browser-window-blur","type":"ui"},{"timestamp":1626100969.245,"category":"console","level":"error","message":"(node:2) UnhandledPromiseRejectionWarning: Error: unauthorized\n    at buildError (<embedded>:10:497792)\n    at IncomingMessage.<anonymous> (<embedded>:10:499489)\n    at IncomingMessage.emit (events.js:310:20)\n    at IncomingMessage.EventEmitter.emit (domain.js:482:12)\n    at endReadableNT (_stream_readable.js:1187:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"},{"timestamp":1626100969.245,"category":"console","level":"error","message":"(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)"},{"timestamp":1626101268.673,"category":"console","level":"error","message":"(node:2) UnhandledPromiseRejectionWarning: Error: unauthorized\n    at buildError (<embedded>:10:497792)\n    at IncomingMessage.<anonymous> (<embedded>:10:499489)\n    at IncomingMessage.emit (events.js:310:20)\n    at IncomingMessage.EventEmitter.emit (domain.js:482:12)\n    at endReadableNT (_stream_readable.js:1187:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"},{"timestamp":1626101268.673,"category":"console","level":"error","message":"(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)"},{"timestamp":1626101619.922,"category":"console","level":"error","message":"(node:2) UnhandledPromiseRejectionWarning: Error: unauthorized\n    at buildError (<embedded>:10:497792)\n    at IncomingMessage.<anonymous> (<embedded>:10:499489)\n    at IncomingMessage.emit (events.js:310:20)\n    at IncomingMessage.EventEmitter.emit (domain.js:482:12)\n    at endReadableNT (_stream_readable.js:1187:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"},{"timestamp":1626101619.922,"category":"console","level":"error","message":"(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)"},{"timestamp":1626101933.883,"category":"console","level":"error","message":"(node:2) UnhandledPromiseRejectionWarning: Error: unauthorized\n    at buildError (<embedded>:10:497792)\n    at IncomingMessage.<anonymous> (<embedded>:10:499489)\n    at IncomingMessage.emit (events.js:310:20)\n    at IncomingMessage.EventEmitter.emit (domain.js:482:12)\n    at endReadableNT (_stream_readable.js:1187:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"},{"timestamp":1626101933.883,"category":"console","level":"error","message":"(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)"}],"_user":{},"_tags":{"arch":"x64","appId":"6de88fa1a3b8d2d163d805d5ae0a3aa28cd58d61"},"_extra":{},"_contexts":{}}